'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VerificarArchivos

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtTotalExpedientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalExpedientes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAplicaDigitalizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAplicaDigitalizacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNoAplicaDigitalizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoAplicaDigitalizacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExpedientesConArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpedientesConArchivos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExpedientesSinArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpedientesSinArchivos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtExpedientesSinArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpedientesSinArchivos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalHojasEsperadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalHojasEsperadas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtImagenesEsperadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImagenesEsperadas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtArchivosLocalizados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArchivosLocalizados As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtArchivosNoLocalizados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArchivosNoLocalizados As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grvDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvDetalle As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnIniciarVerificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIniciarVerificacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkReiniciarContadores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReiniciarContadores As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblVerificados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerificados As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVerificados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVerificados As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInformacionDirectorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInformacionDirectorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEspacioDisco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEspacioDisco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArchivosFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchivosFS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArchivosDirectorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArchivosDirectorio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArchivosDirectorioVinculados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchivosDirectorioVinculados As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArchivosDirectorioVinculados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArchivosDirectorioVinculados As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArchivosDirectorioSinVincular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchivosDirectorioSinVincular As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArchivosDirectorioSinVincular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArchivosDirectorioSinVincular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnActualizarDatosDirectorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizarDatosDirectorio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkGenerarReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGenerarReporte As Global.System.Web.UI.WebControls.CheckBox
End Class
